<!DOCTYPE html> 
<html> 
<head> 
<title>Docs / CASH Music</title> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 

<style type="text/css" /> 
/* TAG RESETS */
html {margin:0;padding:0;}
body {color:#000;background-color:#fff;text-align:left;font:75%/1.5em "helvetica neue",helvetica,arial,sans-serif;margin:0;padding:0;min-height:300px;min-width:750px;}
a {color:#999;text-decoration:none;}
a:hover {text-decoration:underline;}
code {display:block;padding:2em;margin:0 0 1.5em 0;background-color:#ddd;background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPhJREFUeNqk1M0KgkAQAGCFXqSzBwW9KOg5gugBArGD9PN6KhiIl0Vcg0UUfI0QggRJawyKIjNdB/ayO3wMuzszuUEwI6Ku65PjOCvmNiIAyS3LmoE3pYaqqspt254/EFoIkLPruosXQgO1IkMhuJOL53nLL2QI1InAYns+f4EQ0jVNI78S/kJwXARBoKuqSrryOqEGwRivFUU5/iu5CyrDMDQAwX1+eCsEW2UURYYsy7hvq7RBJSHElCQJDem5D6ipJI5jUxRFNLR536EyTdM9z/M+zRR4QlWSJBtBEHzacdJAV6hkB5V4Y+YSm2XZluO4AzMy7gIMAJSSyK1ong48AAAAAElFTkSuQmCC);background-position:left top;background-repeat:no-repeat;margin:0 auto;}
img {border:0;}
ul {padding:0.5em 0 0.5em 1.5em;}
p {margin:0 0 1.5em 0;}
h1 {font-size:3.75em;line-height:1.25em;margin:0;padding:0;}
h2 {font-size:1.5em;line-height:1em;margin:2em 0 0 0;padding:0;padding-bottom:0.25em;}
small {font-size:0.85em;line-height:1.25em;}
small a {color:#000 !important;font-weight:bold;}
table {font-size:0.85em;}

/* GENERAL STYLES */
span.param, span.return {font-weight:bold;}
span.classdescription {font-size:1.5em;}
span.classdescription br {display:none}
ul.nobullets {padding-left:0;}
ul.nobullets li {list-style-type:none;}
div.commentblock {border-left:8px solid #eee;padding-left:12px;}
#pagemenu {position:absolute;top:80px;left:50%;margin-left:-400px;text-align:left;width:220px;text-align:right;}
#pagemenu h2 {margin-top:0.75em;}

/* FORMS */
input {padding:6px 2% 6px 2%;border:1px solid #ccc;width:96%;}
input:active, input:focus {outline:0;border:1px solid #888;}
input.button, a.mockbutton {background-color:#ccc;padding:6px 18px 6px 18px;font-weight:bold;cursor:pointer;width:auto;}
input.button:hover {background-color:#aaa;}
input.checkorradio {width:auto;}
select {padding:6px 3px 6px 3px;border:1px solid #ccc;width:100%;}
select:active, select:focus {outline:2px solid #ff0;}
label {font-size:0.85em;text-transform:uppercase;color:#999;}

/* COLORS */
.usecolor1 {color:#cd074d;}
.usecolor2 {color:#ca8c07;}
.usecolor3 {color:#97b800;}
.usecolor4 {color:#0080c9;}
.usecolor5 {color:#8a00ca;}
.usecolor0 {color:#999;}

/* FOOTER (base code taken from cssstickyfooter.com) */
* {margin-top:0;padding:0;} 
html, body, #wrap {height:100%;}
body > #wrap {height:auto;min-height:100%;}
#mainspc {padding-bottom:90px;padding-top:80px;width:500px;padding-left:300px;margin:0 auto;}
#footer {position:relative;margin-top:-36px;height:36px;color:#666;text-align:left;font-size:0.9em;line-height:1em;clear:both;background-color:#000;}
#footer p {padding:12px 8px 0px 8px;}
#footer a {color:#666;margin-left:24px;}
#footer a:hover {color:#fff;}
#footer .donatelink {color:#999;}

/* ACCESSIBILITY STUFFS */
* a:active, * a:focus, #footer a.donatelink:active, #footer a.donatelink:focus, input.checkorradio:focus, input.checkorradio:active
{outline:2px solid #ff0;background-color:#ff0;color:#000;}
</style>
<link rel="icon" type="image/png" href="https://cashmusic.org/assets/images/icons/cash.png" /> 

</head> 

<body> 
<a href="http://github.com/cashmusic/DIY"><img style="position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub" /></a>
<div id="wrap"> 
	<div id="mainspc">
