<!DOCTYPE html> 
<html> 
<head> 
<title>Docs / CASH Music</title> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 

<style type="text/css" /> 
/* TAG RESETS */
html {margin:0;padding:0;}
body {color:#000;background-color:#fff;text-align:left;font:75%/1.5em "helvetica neue",helvetica,arial,sans-serif;margin:0;padding:0;min-height:300px;min-width:750px;}
a {color:#999;text-decoration:none;}
a:hover {text-decoration:underline;}
code {display:block;padding:2em;margin:0 0 1.5em 0;background-color:#ddd;background-position:left top;background-repeat:no-repeat;margin:0 auto;}
img {border:0;}
ul {padding:0.5em 0 0.5em 1.5em;}
p {margin:0 0 1.5em 0;}
h1 {font-size:3.75em;line-height:1.25em;margin:0;padding:0;}
h2 {font-size:1.5em;line-height:1em;margin:2em 0 0 0;padding:0;padding-bottom:0.25em;}
small {font-size:0.85em;line-height:1.25em;}
small a {color:#000 !important;font-weight:bold;}
table {font-size:0.85em;}

/* GENERAL STYLES */
span.param, span.return {font-weight:bold;}

/* FORMS */
input {padding:6px 2% 6px 2%;border:1px solid #ccc;width:96%;}
input:active, input:focus {outline:0;border:1px solid #888;}
input.button, a.mockbutton {background-color:#ccc;padding:6px 18px 6px 18px;font-weight:bold;cursor:pointer;width:auto;}
input.button:hover {background-color:#aaa;}
input.checkorradio {width:auto;}
select {padding:6px 3px 6px 3px;border:1px solid #ccc;width:100%;}
select:active, select:focus {outline:2px solid #ff0;}
label {font-size:0.85em;text-transform:uppercase;color:#999;}

/* COLORS */
.bgcolor1, div.usecolor1 input.button, div.usecolor1 a.mockbutton {background-color:#df0854;color:#fff;}
.bgcolor2, div.usecolor2 input.button, div.usecolor2 a.mockbutton {background-color:#df9b08;color:#fff;}
.bgcolor3, div.usecolor3 input.button, div.usecolor3 a.mockbutton {background-color:#aacd07;color:#fff;}
.bgcolor4, div.usecolor4 input.button, div.usecolor4 a.mockbutton {background-color:#0891df;color:#fff;}
.bgcolor5, div.usecolor5 input.button, div.usecolor5 a.mockbutton {background-color:#9b08df;color:#fff;}
div.usecolor1 input.button:hover, div.usecolor1 a.mockbutton:hover {background-color:#cd074d;color:#fff;}
div.usecolor2 input.button:hover, div.usecolor2 a.mockbutton:hover {background-color:#ca8c07;color:#fff;}
div.usecolor3 input.button:hover, div.usecolor3 a.mockbutton:hover {background-color:#97b800;color:#fff;}
div.usecolor4 input.button:hover, div.usecolor4 a.mockbutton:hover {background-color:#0080c9;color:#fff;}
div.usecolor5 input.button:hover, div.usecolor5 a.mockbutton:hover {background-color:#8a00ca;color:#fff;}
a.mockbutton {color:#000 !important;font-size:0.9em;}
a.mockbutton:hover {text-decoration:none !important;}
a.loginlink {color:#000;background-color:#ff0;font-size:2.5em;font-weight:bold;padding:0 12px 0 12px;}
a.loginlink:hover {background-color:#fff;}

/* FOOTER (base code taken from cssstickyfooter.com) */
* {margin-top:0;padding:0;} 
html, body, #wrap {height:100%;}
body > #wrap {height:auto;min-height:100%;}
#mainspc {padding-bottom:90px;padding-top:80px;width:400px;margin:0 auto;}
#footer {position:relative;margin-top:-36px;height:36px;color:#666;text-align:left;font-size:0.9em;line-height:1em;clear:both;background-color:#000;}
#footer p {padding:12px 8px 0px 8px;}
#footer a {color:#666;margin-left:24px;}
#footer a:hover {color:#fff;}
#footer .donatelink {color:#999;}

/* ACCESSIBILITY STUFFS */
* a:active, * a:focus, #footer a.donatelink:active, #footer a.donatelink:focus, input.checkorradio:focus, input.checkorradio:active
{outline:2px solid #ff0;background-color:#ff0;color:#000;}
</style>
<link rel="icon" type="image/png" href="https://cashmusic.org/assets/images/icons/cash.png" /> 

</head> 

<body> 

<div id="wrap"> 
 	<div id="mainspc">
